INSERT INTO team (team_name, team_id) VALUES ("Snowman", 6);
INSERT INTO team (team_name, team_id) VALUES ("関ジャニ∞", 7);
INSERT INTO team (team_name, team_id) VALUES ("Sexy Zone", 8);
INSERT INTO team (team_name, team_id) VALUES ("TOKIO", 9);
INSERT INTO team (team_name, team_id) VALUES ("V6", 10);
INSERT INTO team (team_name, team_id) VALUES ("ARASHI", 11);
INSERT INTO team (team_name, team_id) VALUES ("NEWS", 12);
INSERT INTO team (team_name, team_id) VALUES ("Kis-My-Ft2", 13);
INSERT INTO team (team_name, team_id) VALUES ("A.B.C-Z", 14);
INSERT INTO team (team_name, team_id) VALUES ("ジャニーズWEST", 15);
INSERT INTO team (team_name, team_id) VALUES ("King & Prince", 16);