package otaku.info.enums;

import lombok.Getter;

@Getter
public enum StationEnum {

    NHK(1,"NHK総合",0),
    NHK_E(2,"NHKEテレ",0),
    NITTERE(3,"日テレ",0),
    TV_ASAHI(4,"テレビ朝日",0),
    TBS(5,"TBS",0),
    TV_TOKYO(6,"テレビ東京",0),
    FUJI(7,"フジテレビ",0),
    SPACE_SHOWER(8,"音楽・ライブ！　スペースシャワーＴＶ",0),
    SPACE_SHOWER_PLUS(9,"100%ヒッツ！スペースシャワーTVプラス",0),
    BS12(10,"BS12トゥエルビ",0),
    NHK_E_1(11,"ＮＨＫＥテレ１・東京",0),
    NULL(12,"",0),
    NITTERE_PLUS(13,"日テレプラス　ドラマ・アニメ・音楽ライブ",0),
    JIDAIGEKI(14,"時代劇専門チャンネル",0),
    GAORA_SPORTS(15,"GAORASPORTS",0),
    AV(16,"AV王",1),
    MNET(17,"Ｍｎｅｔ",0),
    BS_SCAPA_SPORTS(18,"BSスカパー!スポーツ",0),
    WOWOW_LIVE_MUSIC(19,"ＷＯＷＯＷライブ音楽",0),
    WOWOW(20,"ＷＯＷＯＷ　４Ｋドラマ",0),
    FIGHTING_TV_SAMURAI(21,"FIGHTINGTVサムライ",0),
    WOWOW_PRIME(22,"ＷＯＷＯＷプライム",0),
    TBS_1(23,"ＴＢＳチャンネル１最新ドラマ・音楽・映画",0),
    MUSIC_AIR(24,"ミュージック・エア",0),
    EISEI_GEKIJO(25,"衛星劇場",0),
    TBS_2(26,"ＴＢＳチャンネル２名作ドラマ・スポーツ・アニメ",0),
    SUPER_DRAMA(27,"スーパー！ドラマＴＶ　#海外ドラマ☆エンタメ",0),
    KBS_WORLD(28,"ＫＢＳＷｏｒｌｄ",0),
    TOKYO_MIX(29,"ＴＯＫＹＯ　ＭＸ１",0),
    MTV(30,"MTV",0),
    BS11(31,"BS11イレブン",0),
    SKY_A(32,"スカイA",0),
    SKY_CHANNEL(33,"スカチャン1",0),
    KIDS_ST(34,"キッズステーションテレビアニメ･劇場版･ＯＶＡ",0),
    WOWOW_LIVE(35,"ＷＯＷＯＷライブ",0),
    BS_TBS4K(36,"BS-TBS4Kバラエティー,趣味／教育,情報／ワイドショー",0),
    NHK_BS(37,"ＮＨＫＢＳプレミアム",0),
    BS_TBS(38,"ＢＳ-ＴＢＳ",0),
    BS_FUJI(39,"ＢＳフジ",0),
    BS_NIHON_EIGA(40,"BS日本映画専門チャンネル映画",0),
    NIHON_EIGA(41,"日本映画専門チャンネル",0),
    BS_FUJI_4K_DRAMA(42,"BSフジ4Kドラマ",0),
    NIHON_EIGA_JIDAI(43,"日本映画+時代劇4K",0),
    MUSICON(44,"MUSICON!TV（エムオン!）",0),
    FUJI_NEXT(45,"フジテレビＮＥＸＴ　ライブ・プレミアム",0),
    CARTOON(46,"海外アニメ！カートゥーンネットワーク",0),
    NATIONAL_GEO(47,"ナショナルジオグラフィック",0),
    DANCE(48,"ダンスチャンネルbyエンタメ〜テレ",0),
    TV_ASA_1(49,"テレ朝チャンネル１",0),
    SPORTS_LIVE(50,"スポーツライブ＋",0),
    THE_CINEMA(51,"ザ・シネマ",0),
    ANIME_THEATER(52,"アニメシアターＸ（AT-X）",0),
    BS_TV_TOKYO_4K_ANIME(53,"BSテレ東4Kアニメ／特撮",0),
    BS_TV_TOKYO(54,"ＢＳテレ東",0),
    HOSO_DAIGAKU(55,"放送大学ex趣味／教育,ドキュメンタリー／教養",0),
    BS_TBS_4K(56,"BS-TBS4Kバラエティー,趣味／教育",0),
    KAYO_POPS(57,"歌謡ポップスチャンネル",0),
    NHK_1(58,"ＮＨＫ総合１・東京",0),
    WOWOW_EIGA(59,"ＷＯＷＯＷシネマ映画",0),
    BS_ANIMAX_MUSIC(60,"BSアニマックス音楽",0),
    ANIMAX(61,"アニマックス",0),
    HOME_DRAMA(62,"ホームドラマチャンネル　韓流・時代劇・国内ドラマ",0),
    BS_FUJI_4K(63,"BSフジ4Kバラエティー",0),
    DISCOVERY(64,"ディスカバリーチャンネル",0),
    HOSO_DAI_HOBBY(65,"放送大学on趣味／教育,ドキュメンタリー／教養",0),
    FAMILY_TEATER(66,"ファミリー劇場",0),
    NHK_BS_4K_MUSIC(67,"NHKBS4K音楽",0),
    BS_NITTERE(68,"ＢＳ日テレ",0),
    PLAYBOY(69,"プレイボーイチャンネル",0),
    PACHI(70,"パチ・スロ　サイトセブンＴＶ",0),
    DISNEY(71,"ディズニー･チャンネル",0),
    FUJI_TWO(72,"フジテレビＴＷＯ　ドラマ・アニメ",0),
    STRONG(73,"刺激ストロングチャンネル",0),
    TETSUDO(74,"鉄道チャンネル",0),
    PACHI_TV(75,"パチンコ★パチスロＴＶ！",0),
    STAR_CHANNEL(76,"スター・チャンネル3ドラマ",0),
    DISNEY_JR(77,"ディズニージュニア",0),
    ANIMAL_PLANET(78,"アニマルプラネット",0),
    WOWOW_4K(79,"ＷＯＷＯＷ　４Ｋ映画",0),
    JEWELY(80,"ジュエリー☆ＧＳＴＶ",0),
    MONDO_TV(81,"MONDOTV",0),
    NHK_BS_8K(82,"NHKBS8Kドキュメンタリー／教養",0),
    CHANNEL_GINGA(83,"チャンネル銀河　歴史ドラマ・サスペンス・日本のうた",0),
    BS_TERETO_4K_DRAMA(84,"BSテレ東4Kドラマ",0),
    BS_TBS_4K_EIGA(85,"BS-TBS4K映画",0),
    BS_ANIMAX(86,"BSアニマックスアニメ／特撮",0),
    AXN_MYTHTERY(87,"AXNミステリー",0),
    TV_ASA_2(88,"テレ朝チャンネル２",0),
    WOWOW_PLUS(89,"WOWOWプラス映画",0),
    BS_JP_MOVIE(90,"BS日本映画専門チャンネルドラマ",0),
    BS_ASAHI(91,"ＢＳ朝日",0),
    BS_ASAHI_4K_DRAMA(92,"BS朝日4Kドラマ",0),
    BS_TERETO_4K_JOHO(93,"BSテレ東4K情報／ワイドショー,ドラマ",0),
    JOSEI_CHANNEL(94,"女性チャンネル♪LaLaTV",0),
    NHK_BS_4K_DOCUMENT_HOBBY(95,"NHKBS4Kドキュメンタリー／教養,趣味／教育",0),
    VENUS(96,"VENUS",0),
    NHK_BS1(97,"ＮＨＫＢＳ１",0),
    NHK_E3(98,"ＮＨＫＥテレ３・東京",0),
    TOHO_CHANNEL(99,"東映チャンネル",0),
    AXN_KAIGAI(100,"ＡＸＮ海外ドラマ",0),
    EIGA_CHANNEL(101,"映画・チャンネルNECO",0),
    NITTERE_JIDASU(102,"日テレジータス",0),
    DISNEY_ANIME(103,"ディズニー・チャンネルアニメ／特撮",0),
    STAR(104,"スター・チャンネル3映画",0),
    FUJI_ONE(105,"フジテレビＯＮＥ　スポーツ・バラエティ",0),
    ENTAME(106,"エンタメ〜テレ☆シネドラバラエティ",0),
    NHK_BS_4K_DRAMA(107,"NHKBS4Kドラマ",0),
    BS_NITTERE_4K_ANIME(108,"BS日テレ4Kアニメ／特撮",0),
    NHK_BS_4K_DOCUMENT(109,"NHKBS4Kドキュメンタリー／教養",0),
    STAR_CHANNEL_1(110,"スター・チャンネル1",0),
    IGO(111,"囲碁・将棋チャンネル",0),
    BS_ASAHI_4K_BA(112,"BS朝日4Kバラエティー,趣味／教育,情報／ワイドショー",0);

    private final Integer id;
    private final String name;
    private final Integer note;

    StationEnum(Integer id, String name, Integer note) {
        this.id = id;
        this.name = name;
        this.note = note;
    }
}
