UPDATE item SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
ALTER TABLE item MODIFY created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE team MODIFY team_id INT NOT NULL AUTO_INCREMENT;
