INSERT INTO AFFILI_SEARCH_GENRE (AFFILI_SEARCH_GENRE) VALUES ('雑誌');
INSERT INTO AFFILI_SEARCH_GENRE (AFFILI_SEARCH_GENRE) VALUES ('CD');
INSERT INTO AFFILI_SEARCH_GENRE (AFFILI_SEARCH_GENRE) VALUES ('DVD');