INSERT INTO member (team_id, member_name, kana, mnemonic, birthday) VALUES (6,"岩本 照", "いわもと ひかる", "ひーくん ひかる", "1993-05-17");
INSERT INTO member (team_id, member_name, kana, mnemonic, birthday) VALUES (6,"深澤 辰哉", "ふかさわ しんや", "ふっか", "1992-05-05");
INSERT INTO member (team_id, member_name, kana, mnemonic, birthday) VALUES (6,"渡辺 翔太", "わたなべ しょうた", "しょっぴー", "1992-11-05");
INSERT INTO member (team_id, member_name, kana, mnemonic, birthday) VALUES (6,"阿部 亮平", "あべ りょうた", "あべちゃん", "1993-11-27");
INSERT INTO member (team_id, member_name, kana, mnemonic, birthday) VALUES (6,"宮舘 涼太", "みやだて りょうた", "舘様", "1993-03-25");
INSERT INTO member (team_id, member_name, kana, mnemonic, birthday) VALUES (6,"佐久間 大介", "さくま だいすけ", "さっくん", "1992-07-05");
INSERT INTO member (team_id, member_name, kana, mnemonic, birthday) VALUES (6,"向井 康二", "むかい こうじ", "康二 じーこ", "1994-06-21");
INSERT INTO member (team_id, member_name, kana, mnemonic, birthday) VALUES (6,"目黒 蓮", "めぐろ れん", "めめ", "1997-02-16");
INSERT INTO member (team_id, member_name, kana, mnemonic, birthday) VALUES (6,"ラウール", "らうーる", "ラウール", "2003-06-27");
INSERT INTO member (team_id, member_name, kana, mnemonic, birthday) VALUES (7,"横山 裕", "よこやま ゆう", "よこ よこちょ ゆうちん", "1981-05-10");
INSERT INTO member (team_id, member_name, kana, mnemonic, birthday) VALUES (7,"村上 信五", "むらかみ しんご", "ヒナ しんちゃん", "1982-01-26");
INSERT INTO member (team_id, member_name, kana, mnemonic, birthday) VALUES (7,"丸山 隆平", "まるやま りゅうへい", "まる まるちゃん", "1983-11-26");
INSERT INTO member (team_id, member_name, kana, mnemonic, birthday) VALUES (7,"安田 章大", "やすだ しょうた", "やす しょうちゃん", "1984-09-11");
INSERT INTO member (team_id, member_name, kana, mnemonic, birthday) VALUES (7,"大倉 忠義", "おおくら ただよし", "大倉 たっちょん", "1985-05-16");
INSERT INTO member (team_id, member_name, kana, mnemonic, birthday) VALUES (8,"中島 健人", "なかじま けんと", "健人 ナカケン ナカジー ラブホリ先輩 健人君", "1994-03-13");
INSERT INTO member (team_id, member_name, kana, mnemonic, birthday) VALUES (8,"菊池 風磨", "きくち ふうま", "風磨 ふーま きくふう ふまたん 風磨君", "1995-03-07");
INSERT INTO member (team_id, member_name, kana, mnemonic, birthday) VALUES (8,"佐藤 勝利", "さとう しょうり", "勝利 勝利君 しょりたん", "1996-10-30");
INSERT INTO member (team_id, member_name, kana, mnemonic, birthday) VALUES (8,"松島 聡", "まつしま そう", "聡 まっつー そうちゃん", "1997-11-27");
INSERT INTO member (team_id, member_name, kana, mnemonic, birthday) VALUES (8,"マリウス 葉", "まりうす よう", "マリウス マリウス君 まりちゃん まりたん 葉くん マリー まり 天使", "2000-03-30");
INSERT INTO member (team_id, member_name, kana, mnemonic, birthday) VALUES (17,"ジェシー", "ジェシー", "ジェシー ジェス", "1996-06-11");
INSERT INTO member (team_id, member_name, kana, mnemonic, birthday) VALUES (17,"京本 大我", "きょうもと たいが", "きょも たいが", "1994-12-03");
INSERT INTO member (team_id, member_name, kana, mnemonic, birthday) VALUES (17,"松村 北斗", "まつむら ほくと", "ほくと ほっくん", "1995-06-18");
INSERT INTO member (team_id, member_name, kana, mnemonic, birthday) VALUES (17,"田中 樹", "たなか じゅり", "じゅり じゅったん", "1995-06-15");
INSERT INTO member (team_id, member_name, kana, mnemonic, birthday) VALUES (17,"高地 優吾", "こうち ゆうご", "こうち おじいちゃん", "1994-03-08");
INSERT INTO member (team_id, member_name, kana, mnemonic, birthday) VALUES (17,"森本 慎太郎", "もりもと しんたろう", "しんたろう 慎ちゃん", "1997-07-15");
INSERT INTO member (team_id, member_name, kana, mnemonic, birthday) VALUES (16,"平野 紫耀", "ひらの しょう", "しょう ひらのん", "1997-01-29");
INSERT INTO member (team_id, member_name, kana, mnemonic, birthday) VALUES (16,"永瀬 廉", "ながせ れん", "れんれん れんくん", "1999-01-23");
INSERT INTO member (team_id, member_name, kana, mnemonic, birthday) VALUES (16,"髙橋 海人", "たかはし かいと", "かいと たかいと かいちゃん かい", "1999-04-03");
INSERT INTO member (team_id, member_name, kana, mnemonic, birthday) VALUES (16,"岸 優太", "きし ゆうた", "岸くん こしくん 優太 優太くん", "1995-09-29");
INSERT INTO member (team_id, member_name, kana, mnemonic, birthday) VALUES (16,"神宮寺 勇太", "じんぐうじ ゆうた", "じん じんくん じぐたん チャラぐうじ", "1997-10-30");